import { useState } from 'react'
import { useNavigate } from '@tanstack/react-router'

const MOCK_INBOX_DATA = [
  {
    id: '1',
    fileName: 'comprovante-residencia.pdf',
    fileSize: '2.4 MB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Mariana Costa Silva',
    contactInfo: 'Portal do cliente · mariana.silva@email.com',
    caseId: 'Caso 0089',
    caseDesc: 'Comprovante de residência',
    receivedDate: 'Hoje',
    receivedTime: '14:32',
    status: 'Aguardando validação',
    badgeVariant: 'secondary',
  },
  {
    id: '2',
    fileName: 'extrato-bancario.pdf',
    fileSize: '1.1 MB',
    receivedFromIcon: 'message-circle',
    receivedFrom: 'João Paulo Mendes',
    contactInfo: 'WhatsApp · +55 21 99876-5432',
    caseId: 'Caso 0091',
    caseDesc: 'Extrato bancário',
    receivedDate: 'Hoje',
    receivedTime: '13:08',
    status: 'Validado',
    badgeVariant: 'success',
  },
  {
    id: '3',
    fileName: 'rg-frente-verso.jpg',
    fileSize: '3.8 MB',
    receivedFromIcon: 'mail',
    receivedFrom: 'Ana Beatriz Lima',
    contactInfo: 'E-mail · ana.lima@email.com',
    caseId: 'Sem vínculo seguro',
    caseDesc: 'Escolha manual necessária',
    receivedDate: 'Ontem',
    receivedTime: '17:45',
    status: 'Ilegível',
    badgeVariant: 'destructive',
  },
  {
    id: '4',
    fileName: 'contrato-social.pdf',
    fileSize: '890 KB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Alvorada Serviços Ltda.',
    contactInfo: 'Portal do cliente · documentos@alvorada.com.br',
    caseId: 'Caso 0094',
    caseDesc: 'Contrato social',
    receivedDate: 'Ontem',
    receivedTime: '16:20',
    status: 'Incompleto',
    badgeVariant: 'attention',
  },
  {
    id: '5',
    fileName: 'declaracao-hipossuficiencia.pdf',
    fileSize: '620 KB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Rafael Nunes',
    contactInfo: 'Portal do cliente · rafael.nunes@email.com',
    caseId: 'Caso 0087',
    caseDesc: 'Declaração de hipossuficiência',
    receivedDate: 'Ontem',
    receivedTime: '15:02',
    status: 'Duplicado',
    badgeVariant: 'outline',
  },
  {
    id: '6',
    fileName: 'procuracao-assinada.pdf',
    fileSize: '740 KB',
    receivedFromIcon: 'message-circle',
    receivedFrom: 'Cláudia Ferreira',
    contactInfo: 'WhatsApp · +55 11 98765-1098',
    caseId: 'Caso não identificado',
    caseDesc: 'Análise interrompida',
    receivedDate: '05/08/2026',
    receivedTime: '11:26',
    status: 'Falha no processamento',
    badgeVariant: 'destructive',
  },
  {
    id: '7',
    fileName: 'cnh-motorista.pdf',
    fileSize: '1.2 MB',
    receivedFromIcon: 'mail',
    receivedFrom: 'Carlos Almeida',
    contactInfo: 'E-mail · carlos.almeida@email.com',
    caseId: 'Caso 0102',
    caseDesc: 'CNH',
    receivedDate: '04/08/2026',
    receivedTime: '09:15',
    status: 'Aguardando validação',
    badgeVariant: 'secondary',
  },
  {
    id: '8',
    fileName: 'holerite-mes-anterior.pdf',
    fileSize: '450 KB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Fernanda Lima',
    contactInfo: 'Portal do cliente · fernanda.lima@email.com',
    caseId: 'Caso 0105',
    caseDesc: 'Comprovante de renda',
    receivedDate: '04/08/2026',
    receivedTime: '14:20',
    status: 'Aguardando validação',
    badgeVariant: 'secondary',
  },
  {
    id: '9',
    fileName: 'certidao-nascimento.jpg',
    fileSize: '4.1 MB',
    receivedFromIcon: 'message-circle',
    receivedFrom: 'Roberto Gomes',
    contactInfo: 'WhatsApp · +55 11 91234-5678',
    caseId: 'Caso 0110',
    caseDesc: 'Certidão de nascimento',
    receivedDate: '03/08/2026',
    receivedTime: '16:40',
    status: 'Ilegível',
    badgeVariant: 'destructive',
  },
  {
    id: '10',
    fileName: 'comprovante-pix.png',
    fileSize: '800 KB',
    receivedFromIcon: 'message-circle',
    receivedFrom: 'Juliana Souza',
    contactInfo: 'WhatsApp · +55 21 98888-7777',
    caseId: 'Caso 0112',
    caseDesc: 'Comprovante de pagamento',
    receivedDate: '03/08/2026',
    receivedTime: '10:05',
    status: 'Validado',
    badgeVariant: 'success',
  },
  {
    id: '11',
    fileName: 'carteira-trabalho.pdf',
    fileSize: '3.2 MB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Marcos Silva',
    contactInfo: 'Portal do cliente · marcos.silva@email.com',
    caseId: 'Caso 0115',
    caseDesc: 'CTPS',
    receivedDate: '02/08/2026',
    receivedTime: '11:30',
    status: 'Incompleto',
    badgeVariant: 'attention',
  },
  {
    id: '12',
    fileName: 'laudo-medico.pdf',
    fileSize: '5.5 MB',
    receivedFromIcon: 'mail',
    receivedFrom: 'Patrícia Ribeiro',
    contactInfo: 'E-mail · patricia.ribeiro@email.com',
    caseId: 'Sem vínculo seguro',
    caseDesc: 'Escolha manual necessária',
    receivedDate: '02/08/2026',
    receivedTime: '15:50',
    status: 'Aguardando validação',
    badgeVariant: 'secondary',
  },
  {
    id: '13',
    fileName: 'boletim-ocorrencia.pdf',
    fileSize: '1.8 MB',
    receivedFromIcon: 'circle-help',
    receivedFrom: 'Thiago Martins',
    contactInfo: 'Portal do cliente · thiago.martins@email.com',
    caseId: 'Caso 0118',
    caseDesc: 'Boletim de ocorrência',
    receivedDate: '01/08/2026',
    receivedTime: '08:45',
    status: 'Validado',
    badgeVariant: 'success',
  },
  {
    id: '14',
    fileName: 'fatura-cartao.pdf',
    fileSize: '950 KB',
    receivedFromIcon: 'message-circle',
    receivedFrom: 'Camila Rocha',
    contactInfo: 'WhatsApp · +55 31 97777-6666',
    caseId: 'Caso 0120',
    caseDesc: 'Comprovante de residência',
    receivedDate: '01/08/2026',
    receivedTime: '13:15',
    status: 'Duplicado',
    badgeVariant: 'outline',
  },
  {
    id: '15',
    fileName: 'contrato-aluguel.pdf',
    fileSize: '2.1 MB',
    receivedFromIcon: 'mail',
    receivedFrom: 'Lucas Pereira',
    contactInfo: 'E-mail · lucas.pereira@email.com',
    caseId: 'Caso 0122',
    caseDesc: 'Contrato de locação',
    receivedDate: '31/07/2026',
    receivedTime: '17:20',
    status: 'Aguardando validação',
    badgeVariant: 'secondary',
  },
] as const

export function useDocumentInbox() {
  const navigate = useNavigate()
  const [currentPage, setCurrentPage] = useState(1)
  const itemsPerPage = 6

  const totalItems = MOCK_INBOX_DATA.length
  const totalPages = Math.ceil(totalItems / itemsPerPage)

  const paginatedData = MOCK_INBOX_DATA.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage,
  )

  const handlePageChange = (page: number) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page)
    }
  }

  const handleAnalyze = (fileId: string) => {
    navigate({
      to: '/caixa-de-documentos/$fileId',
      params: { fileId },
    })
  }

  const handleRefresh = () => {
    window.location.reload()
  }

  return {
    currentPage,
    totalPages,
    totalItems,
    paginatedData,
    handlePageChange,
    handleAnalyze,
    handleRefresh,
  }
}