import { Module } from '@nestjs/common'

import {
  FORMALIZATION_DATABASE_OPERATIONS,
  FORMALIZATION_REPOSITORIES,
} from '@/formalization/constants/formalization-repositories'
import { FORMALIZATION_PROVIDERS } from '@/formalization/constants/formalization-providers'
import { FormalizationSeeder } from '@/formalization/database/formalization-seeder'
import {
  DrizzleFormalizationMapper,
  DrizzleFormalizationSignatureArtifactMapper,
  DrizzleFormalizationSignatureAuditEntryMapper,
  DrizzleFormalizationSignatureCancellationAttemptMapper,
  DrizzleFormalizationSignatureGatewaySessionMapper,
  DrizzleFormalizationSignatureInvitationMapper,
  DrizzleFormalizationSignatureInvitationSendAttemptMapper,
  DrizzleFormalizationSignatureOtpChallengeMapper,
  DrizzleFormalizationSignatureOtpGuardMapper,
  DrizzleFormalizationSignatureOtpRateReservationMapper,
  DrizzleFormalizationSignatureOtpSendAttemptMapper,
  DrizzleFormalizationSignatureProviderRecipientResourceMapper,
  DrizzleFormalizationSignatureProviderResourceMapper,
  DrizzleFormalizationSignatureProvisioningAttemptMapper,
  DrizzleFormalizationSignatureProxyBindingMapper,
  DrizzleFormalizationSignatureProtocolMapper,
  DrizzleFormalizationSignatureRecipientMapper,
  DrizzleFormalizationSignatureRequestDocumentMapper,
  DrizzleFormalizationSignatureRequestMapper,
  DrizzleFormalizationSignatureSnapshotMapper,
  DrizzleFormalizationSignatureWebhookReceiptMapper,
  DrizzleFormalizationSignatureMapper,
  DrizzleFormalizationSignatureRecipientDocumentMapper,
  DrizzleFormalizationSignatureProviderDocumentResourceMapper,
  DrizzleFormalizationSignatureDocumentAcknowledgementMapper,
} from '@/formalization/database/drizzle/mappers'
import {
  DrizzleFormalizationsRepository,
  DrizzleFormalizationSignatureArtifactsRepository,
  DrizzleFormalizationSignatureAuditWriter,
  DrizzleFormalizationSignatureCancellationAttemptsRepository,
  DrizzleFormalizationSignatureGatewaySessionsRepository,
  DrizzleFormalizationSignatureInvitationSendAttemptsRepository,
  DrizzleFormalizationSignatureInvitationsRepository,
  DrizzleFormalizationSignatureOtpChallengesRepository,
  DrizzleFormalizationSignatureOtpGuardsRepository,
  DrizzleFormalizationSignatureOtpRateReservationsRepository,
  DrizzleFormalizationSignatureOtpSendAttemptsRepository,
  DrizzleFormalizationSignatureProviderRecipientResourcesRepository,
  DrizzleFormalizationSignatureProviderResourcesRepository,
  DrizzleFormalizationSignatureProvisioningAttemptsRepository,
  DrizzleFormalizationSignatureProxyBindingsRepository,
  DrizzleFormalizationSignatureProtocolsRepository,
  DrizzleFormalizationSignatureRecipientsRepository,
  DrizzleFormalizationSignatureRequestDocumentsRepository,
  DrizzleFormalizationSignatureRequestsRepository,
  DrizzleFormalizationSignatureSnapshotsRepository,
  DrizzleFormalizationSignatureWebhookReceiptsRepository,
  DrizzleFormalizationSignatureConfigurationRepository,
  DrizzleFormalizationSignatureRecipientDocumentsRepository,
  DrizzleFormalizationSignatureProviderDocumentResourcesRepository,
  DrizzleFormalizationSignatureDocumentAcknowledgementsRepository,
} from '@/formalization/database/drizzle/repositories'
import { DrizzleFormalizationSignatureGatewayTransaction } from '@/formalization/database/formalization-signature-gateway-transaction'
import { SharedDatabaseModule } from '@/shared/database/drizzle/database.module'
import { FormalizationProvisionModule } from '@/formalization/provision/formalization-provision.module'
import { DrizzleFormalizationSignatureInvitationResendTransaction } from '@/formalization/database/formalization-signature-invitation-resend-transaction'

@Module({
  imports: [SharedDatabaseModule, FormalizationProvisionModule],
  providers: [
    DrizzleFormalizationMapper,
    DrizzleFormalizationsRepository,
    DrizzleFormalizationSignatureMapper,
    DrizzleFormalizationSignatureConfigurationRepository,
    DrizzleFormalizationSignatureSnapshotMapper,
    DrizzleFormalizationSignatureRequestMapper,
    DrizzleFormalizationSignatureRequestDocumentMapper,
    DrizzleFormalizationSignatureRecipientMapper,
    DrizzleFormalizationSignatureInvitationMapper,
    DrizzleFormalizationSignatureInvitationSendAttemptMapper,
    DrizzleFormalizationSignatureProviderResourceMapper,
    DrizzleFormalizationSignatureProviderRecipientResourceMapper,
    DrizzleFormalizationSignatureProvisioningAttemptMapper,
    DrizzleFormalizationSignatureCancellationAttemptMapper,
    DrizzleFormalizationSignatureOtpGuardMapper,
    DrizzleFormalizationSignatureOtpChallengeMapper,
    DrizzleFormalizationSignatureOtpSendAttemptMapper,
    DrizzleFormalizationSignatureOtpRateReservationMapper,
    DrizzleFormalizationSignatureGatewaySessionMapper,
    DrizzleFormalizationSignatureProxyBindingMapper,
    DrizzleFormalizationSignatureWebhookReceiptMapper,
    DrizzleFormalizationSignatureArtifactMapper,
    DrizzleFormalizationSignatureProtocolMapper,
    DrizzleFormalizationSignatureAuditEntryMapper,
    DrizzleFormalizationSignatureRecipientDocumentMapper,
    DrizzleFormalizationSignatureProviderDocumentResourceMapper,
    DrizzleFormalizationSignatureDocumentAcknowledgementMapper,
    DrizzleFormalizationSignatureSnapshotsRepository,
    DrizzleFormalizationSignatureRequestsRepository,
    DrizzleFormalizationSignatureRequestDocumentsRepository,
    DrizzleFormalizationSignatureRecipientsRepository,
    DrizzleFormalizationSignatureInvitationsRepository,
    DrizzleFormalizationSignatureInvitationSendAttemptsRepository,
    DrizzleFormalizationSignatureProviderResourcesRepository,
    DrizzleFormalizationSignatureProviderRecipientResourcesRepository,
    DrizzleFormalizationSignatureProvisioningAttemptsRepository,
    DrizzleFormalizationSignatureCancellationAttemptsRepository,
    DrizzleFormalizationSignatureOtpGuardsRepository,
    DrizzleFormalizationSignatureOtpChallengesRepository,
    DrizzleFormalizationSignatureOtpSendAttemptsRepository,
    DrizzleFormalizationSignatureOtpRateReservationsRepository,
    DrizzleFormalizationSignatureGatewaySessionsRepository,
    DrizzleFormalizationSignatureProxyBindingsRepository,
    DrizzleFormalizationSignatureWebhookReceiptsRepository,
    DrizzleFormalizationSignatureArtifactsRepository,
    DrizzleFormalizationSignatureProtocolsRepository,
    DrizzleFormalizationSignatureAuditWriter,
    DrizzleFormalizationSignatureRecipientDocumentsRepository,
    DrizzleFormalizationSignatureProviderDocumentResourcesRepository,
    DrizzleFormalizationSignatureDocumentAcknowledgementsRepository,
    DrizzleFormalizationSignatureGatewayTransaction,
    DrizzleFormalizationSignatureInvitationResendTransaction,
    FormalizationSeeder,
    {
      provide: FORMALIZATION_REPOSITORIES.formalizations,
      useExisting: DrizzleFormalizationsRepository,
    },
    {
      provide: FORMALIZATION_PROVIDERS.signatureConfigurationRepository,
      useExisting: DrizzleFormalizationSignatureConfigurationRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureSnapshots,
      useExisting: DrizzleFormalizationSignatureSnapshotsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureRequests,
      useExisting: DrizzleFormalizationSignatureRequestsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureRequestDocuments,
      useExisting: DrizzleFormalizationSignatureRequestDocumentsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureRecipients,
      useExisting: DrizzleFormalizationSignatureRecipientsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureRecipientDocuments,
      useExisting: DrizzleFormalizationSignatureRecipientDocumentsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureDocumentAcknowledgements,
      useExisting: DrizzleFormalizationSignatureDocumentAcknowledgementsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureInvitations,
      useExisting: DrizzleFormalizationSignatureInvitationsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureInvitationSendAttempts,
      useExisting: DrizzleFormalizationSignatureInvitationSendAttemptsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProviderResources,
      useExisting: DrizzleFormalizationSignatureProviderResourcesRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProviderDocumentResources,
      useExisting: DrizzleFormalizationSignatureProviderDocumentResourcesRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProviderRecipientResources,
      useExisting: DrizzleFormalizationSignatureProviderRecipientResourcesRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProvisioningAttempts,
      useExisting: DrizzleFormalizationSignatureProvisioningAttemptsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureCancellationAttempts,
      useExisting: DrizzleFormalizationSignatureCancellationAttemptsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureOtpGuards,
      useExisting: DrizzleFormalizationSignatureOtpGuardsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureOtpChallenges,
      useExisting: DrizzleFormalizationSignatureOtpChallengesRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureOtpSendAttempts,
      useExisting: DrizzleFormalizationSignatureOtpSendAttemptsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureOtpRateReservations,
      useExisting: DrizzleFormalizationSignatureOtpRateReservationsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureGatewaySessions,
      useExisting: DrizzleFormalizationSignatureGatewaySessionsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProxyBindings,
      useExisting: DrizzleFormalizationSignatureProxyBindingsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureWebhookReceipts,
      useExisting: DrizzleFormalizationSignatureWebhookReceiptsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureArtifacts,
      useExisting: DrizzleFormalizationSignatureArtifactsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureProtocols,
      useExisting: DrizzleFormalizationSignatureProtocolsRepository,
    },
    {
      provide: FORMALIZATION_REPOSITORIES.signatureAuditWriter,
      useExisting: DrizzleFormalizationSignatureAuditWriter,
    },
    {
      provide: FORMALIZATION_DATABASE_OPERATIONS.signatureGatewayTransaction,
      useExisting: DrizzleFormalizationSignatureGatewayTransaction,
    },
    {
      provide: FORMALIZATION_DATABASE_OPERATIONS.invitationResendTransaction,
      useExisting: DrizzleFormalizationSignatureInvitationResendTransaction,
    },
  ],
  exports: [
    FORMALIZATION_REPOSITORIES.formalizations,
    FormalizationSeeder,
    FORMALIZATION_PROVIDERS.signatureConfigurationRepository,
    FORMALIZATION_DATABASE_OPERATIONS.signatureGatewayTransaction,
    FORMALIZATION_REPOSITORIES.signatureSnapshots,
    FORMALIZATION_REPOSITORIES.signatureRequests,
    FORMALIZATION_REPOSITORIES.signatureRequestDocuments,
    FORMALIZATION_REPOSITORIES.signatureRecipients,
    FORMALIZATION_REPOSITORIES.signatureRecipientDocuments,
    FORMALIZATION_REPOSITORIES.signatureDocumentAcknowledgements,
    FORMALIZATION_REPOSITORIES.signatureInvitations,
    FORMALIZATION_REPOSITORIES.signatureInvitationSendAttempts,
    FORMALIZATION_REPOSITORIES.signatureProviderResources,
    FORMALIZATION_REPOSITORIES.signatureProviderDocumentResources,
    FORMALIZATION_REPOSITORIES.signatureProviderRecipientResources,
    FORMALIZATION_REPOSITORIES.signatureProvisioningAttempts,
    FORMALIZATION_REPOSITORIES.signatureCancellationAttempts,
    FORMALIZATION_REPOSITORIES.signatureOtpGuards,
    FORMALIZATION_REPOSITORIES.signatureOtpChallenges,
    FORMALIZATION_REPOSITORIES.signatureOtpSendAttempts,
    FORMALIZATION_REPOSITORIES.signatureOtpRateReservations,
    FORMALIZATION_REPOSITORIES.signatureGatewaySessions,
    FORMALIZATION_REPOSITORIES.signatureProxyBindings,
    FORMALIZATION_REPOSITORIES.signatureWebhookReceipts,
    FORMALIZATION_REPOSITORIES.signatureArtifacts,
    FORMALIZATION_REPOSITORIES.signatureProtocols,
    FORMALIZATION_REPOSITORIES.signatureAuditWriter,
    FORMALIZATION_DATABASE_OPERATIONS.invitationResendTransaction,
  ],
})
export class FormalizationDatabaseModule {}
