export * from '@/intake/database/drizzle/models'
export * from '@/identity/database/drizzle/models'
export * from '@/legal-catalog/database/drizzle/models'
export * from '@/document-production/database/drizzle/models'
export * from '@/communication/database/drizzle/models/communication-model'
export * from '@/communication/database/drizzle/models/private-message-model'
export * from '@/shared/database/drizzle/schema/integracao-evento'

export * from '@/shared/database/drizzle/schema/scheduling'
export * from '@/documents/database/drizzle/models/index'
export * from '@/documents/database/drizzle/models/document-status-model'
