import { z } from 'zod'

const dynamicFormStageSchema = z.enum(['consultation', 'formalization'])

const uuidSchema = z.uuid()
// Existing dynamic-form definitions may contain legacy non-UUID field/option IDs.
// New identifiers are still generated by the Core use cases; this schema only
// needs to preserve valid persisted references across the editor boundary.
const persistentIdentifierSchema = z.string().trim().min(1).max(160)

const trimmedRequiredTextSchema = z.string().trim().min(1).max(160)

const optionalTrimmedTextSchema = z
  .string()
  .trim()
  .max(500)
  .transform((value) => value || undefined)
  .optional()

const optionalPlaceholderSchema = z
  .string()
  .trim()
  .max(160)
  .transform((value) => value || undefined)
  .optional()

const optionalTextDefaultSchema = z
  .string()
  .trim()
  .transform((value) => value || undefined)
  .optional()

const finiteNumberSchema = z.number().finite()
const safeIntegerSchema = finiteNumberSchema.int().safe()

function hasAtMostDecimalPlaces(value: number, decimalPlaces: number): boolean {
  const [coefficient, exponentPart] = value.toString().toLowerCase().split('e')
  const coefficientDecimalPlaces = coefficient.split('.')[1]?.length ?? 0
  const exponent = exponentPart ? Number(exponentPart) : 0
  const actualDecimalPlaces = Math.max(0, coefficientDecimalPlaces - exponent)

  return actualDecimalPlaces <= decimalPlaces
}

const requiredWhenSchema = z
  .object({
    fieldKey: z.string().trim().min(1),
    equals: z.union([z.string(), z.boolean(), finiteNumberSchema]),
  })
  .strict()

const legacyValidationFields = {
  requiredWhen: requiredWhenSchema.optional(),
}

const numericValidationFields = {
  min: finiteNumberSchema.optional(),
  max: finiteNumberSchema.optional(),
  scale: safeIntegerSchema.min(0).max(4).optional(),
  requiredWhen: requiredWhenSchema.optional(),
}

const compatibleValidationSchema = z.object(legacyValidationFields).strict()

const numericValidationSchema = z.object(numericValidationFields).strict()

const optionDraftSchema = z
  .object({
    optionId: persistentIdentifierSchema.optional(),
    label: trimmedRequiredTextSchema,
  })
  .strict()

const selectionOptionsSchema = z.array(optionDraftSchema).min(1)

const defaultOptionIndexSchema = safeIntegerSchema.nonnegative()

const defaultOptionIndexesSchema = z
  .array(defaultOptionIndexSchema)
  .superRefine((indexes, context) => {
    for (let index = 1; index < indexes.length; index += 1) {
      if (indexes[index] <= indexes[index - 1]) {
        context.addIssue({
          code: 'custom',
          message: 'Os índices padrão devem ser únicos e estar em ordem crescente.',
        })
      }
    }
  })
  .transform((indexes) => (indexes.length > 0 ? indexes : undefined))
  .optional()

const dynamicFormDefinitionFieldDraftBaseSchema = z.object({
  fieldId: persistentIdentifierSchema.optional(),
  label: trimmedRequiredTextSchema,
  required: z.boolean(),
  description: optionalTrimmedTextSchema,
})

const textFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('short_text'),
    placeholder: optionalPlaceholderSchema,
    defaultValue: optionalTextDefaultSchema,
    validation: compatibleValidationSchema.optional(),
  })
  .strict()

const longTextFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('long_text'),
    placeholder: optionalPlaceholderSchema,
    defaultValue: optionalTextDefaultSchema,
    validation: compatibleValidationSchema.optional(),
  })
  .strict()

const dateFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('date'),
    defaultValue: z.iso.date().optional(),
    validation: compatibleValidationSchema.optional(),
  })
  .strict()

const booleanFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('boolean'),
    defaultValue: z.boolean().optional(),
    validation: compatibleValidationSchema.optional(),
  })
  .strict()

const multipleSelectionFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('multiple_selection'),
    options: selectionOptionsSchema,
    defaultOptionIndexes: defaultOptionIndexesSchema,
    validation: compatibleValidationSchema.optional(),
  })
  .strict()
  .superRefine((field, context) => {
    if (!field.defaultOptionIndexes) return

    for (const index of field.defaultOptionIndexes) {
      if (index >= field.options.length) {
        context.addIssue({
          code: 'custom',
          message: 'O índice padrão deve apontar para uma opção enviada.',
          path: ['defaultOptionIndexes'],
        })
      }
    }
  })

const singleSelectionFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('single_selection'),
    placeholder: optionalPlaceholderSchema,
    options: selectionOptionsSchema,
    defaultOptionIndex: defaultOptionIndexSchema.optional(),
    validation: compatibleValidationSchema.optional(),
  })
  .strict()
  .superRefine((field, context) => {
    if (field.defaultOptionIndex === undefined) return

    if (field.defaultOptionIndex >= field.options.length) {
      context.addIssue({
        code: 'custom',
        message: 'O índice padrão deve apontar para uma opção enviada.',
        path: ['defaultOptionIndex'],
      })
    }
  })

const integerFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('integer'),
    placeholder: optionalPlaceholderSchema,
    defaultValue: safeIntegerSchema.optional(),
    validation: numericValidationSchema.optional(),
  })
  .strict()

const currencyFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('currency'),
    placeholder: optionalPlaceholderSchema,
    defaultValue: finiteNumberSchema
      .refine((value) => hasAtMostDecimalPlaces(value, 2), {
        message: 'O valor padrão deve ter no máximo duas casas decimais.',
      })
      .optional(),
    currency: z.literal('BRL'),
    validation: numericValidationSchema.optional(),
  })
  .strict()

const percentageValidationSchema = z
  .object({
    ...numericValidationFields,
    scale: safeIntegerSchema.min(0).max(4).default(2),
  })
  .strict()

const percentageFieldSchema = dynamicFormDefinitionFieldDraftBaseSchema
  .extend({
    type: z.literal('percentage'),
    placeholder: optionalPlaceholderSchema,
    defaultValue: finiteNumberSchema.min(0).max(100).optional(),
    validation: percentageValidationSchema.default({ scale: 2 }),
  })
  .strict()
  .superRefine((field, context) => {
    if (field.defaultValue === undefined) return

    const scale = field.validation.scale
    if (!hasAtMostDecimalPlaces(field.defaultValue, scale)) {
      context.addIssue({
        code: 'custom',
        message: 'O valor padrão excede a escala configurada.',
        path: ['defaultValue'],
      })
    }
  })

const dynamicFormDefinitionFieldSchema = z.discriminatedUnion('type', [
  textFieldSchema,
  longTextFieldSchema,
  dateFieldSchema,
  booleanFieldSchema,
  multipleSelectionFieldSchema,
  singleSelectionFieldSchema,
  integerFieldSchema,
  currencyFieldSchema,
  percentageFieldSchema,
])

const uniqueUuidArraySchema = z
  .array(uuidSchema)
  .min(1)
  .superRefine((ids, context) => {
    if (new Set(ids).size !== ids.length) {
      context.addIssue({
        code: 'custom',
        message: 'Os tópicos selecionados devem ser únicos.',
      })
    }
  })

export const dynamicFormDefinitionSchema = z
  .object({
    name: trimmedRequiredTextSchema,
    description: optionalTrimmedTextSchema,
    stage: dynamicFormStageSchema,
    legalAreaId: uuidSchema,
    legalTopicIds: uniqueUuidArraySchema,
    fields: z.array(dynamicFormDefinitionFieldSchema).min(1),
  })
  .strict()

export const createDynamicFormSchema = dynamicFormDefinitionSchema
  .extend({
    operationKey: uuidSchema,
  })
  .strict()

export const updateDynamicFormSchema = dynamicFormDefinitionSchema
  .extend({
    expectedVersion: safeIntegerSchema.positive(),
    operationKey: uuidSchema,
  })
  .strict()

export type DynamicFormDefinitionInput = z.infer<typeof dynamicFormDefinitionSchema>
export type CreateDynamicFormInput = z.infer<typeof createDynamicFormSchema>
export type UpdateDynamicFormInput = z.infer<typeof updateDynamicFormSchema>
