/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntakesRouteRouteImport } from './routes/intakes/route'
import { Route as ConsultasRouteRouteImport } from './routes/consultas/route'
import { Route as ClienteRouteRouteImport } from './routes/cliente/route'
import { Route as AtendimentoRouteRouteImport } from './routes/atendimento/route'
import { Route as AgendaRouteRouteImport } from './routes/agenda/route'
import { Route as AdvogadoRouteRouteImport } from './routes/advogado/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedefinirSenhaIndexRouteImport } from './routes/redefinir-senha/index'
import { Route as PedirRedefinirSenhaIndexRouteImport } from './routes/pedir-redefinir-senha/index'
import { Route as ModelosDeDocumentosIndexRouteImport } from './routes/modelos-de-documentos/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as IntakesIndexRouteImport } from './routes/intakes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ConviteIndexRouteImport } from './routes/convite/index'
import { Route as ConsultasIndexRouteImport } from './routes/consultas/index'
import { Route as ColaboradoresIndexRouteImport } from './routes/colaboradores/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as CaixaDeDocumentosIndexRouteImport } from './routes/caixa-de-documentos/index'
import { Route as AgendaIndexRouteImport } from './routes/agenda/index'
import { Route as ModelosDeDocumentosNovoRouteImport } from './routes/modelos-de-documentos/novo'
import { Route as ModelosDeDocumentosDocumentSpecificationIdRouteImport } from './routes/modelos-de-documentos/$documentSpecificationId'
import { Route as LotesDocumentosFileIdRouteImport } from './routes/lotes-documentos/$fileId'
import { Route as IntakesNovoRouteImport } from './routes/intakes/novo'
import { Route as IntakesIntakeIdRouteImport } from './routes/intakes/$intakeId'
import { Route as ColaboradoresColaboradorIdRouteImport } from './routes/colaboradores/$colaboradorId'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes/$clienteId'
import { Route as ClientePrivacidadeRouteImport } from './routes/cliente/privacidade'
import { Route as ClienteMensagensRouteImport } from './routes/cliente/mensagens'
import { Route as CaixaDeDocumentosFileIdRouteImport } from './routes/caixa-de-documentos/$fileId'
import { Route as AtendimentoDashboardRouteImport } from './routes/atendimento/dashboard'
import { Route as AtendimentoConsultasRouteImport } from './routes/atendimento/consultas'
import { Route as AdvogadoMeusCasosRouteImport } from './routes/advogado/meus-casos'
import { Route as AdvogadoComunicacaoRouteImport } from './routes/advogado/comunicacao'
import { Route as ConsultasConsultationIdRouteRouteImport } from './routes/consultas/$consultationId/route'
import { Route as ConsultasConsultationIdIndexRouteImport } from './routes/consultas/$consultationId/index'
import { Route as ClienteMeusCasosIndexRouteImport } from './routes/cliente/meus-casos/index'
import { Route as ConsultasConsultationIdFichaAtendimentoRouteImport } from './routes/consultas/$consultationId/ficha-atendimento'
import { Route as ClienteMeusCasosCaseIdRouteImport } from './routes/cliente/meus-casos/$caseId'
import { Route as ConsultasConsultationIdDocumentosIndexRouteImport } from './routes/consultas/$consultationId/documentos/index'
import { Route as ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRouteImport } from './routes/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'

const IntakesRouteRoute = IntakesRouteRouteImport.update({
  id: '/intakes',
  path: '/intakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRouteRoute = ConsultasRouteRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRouteRoute = ClienteRouteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRouteRoute = AtendimentoRouteRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRouteRoute = AgendaRouteRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadoRouteRoute = AdvogadoRouteRouteImport.update({
  id: '/advogado',
  path: '/advogado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaIndexRoute = RedefinirSenhaIndexRouteImport.update({
  id: '/redefinir-senha/',
  path: '/redefinir-senha/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirRedefinirSenhaIndexRoute =
  PedirRedefinirSenhaIndexRouteImport.update({
    id: '/pedir-redefinir-senha/',
    path: '/pedir-redefinir-senha/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelosDeDocumentosIndexRoute =
  ModelosDeDocumentosIndexRouteImport.update({
    id: '/modelos-de-documentos/',
    path: '/modelos-de-documentos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakesIndexRoute = IntakesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntakesRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteIndexRoute = ConviteIndexRouteImport.update({
  id: '/convite/',
  path: '/convite/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasIndexRoute = ConsultasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultasRouteRoute,
} as any)
const ColaboradoresIndexRoute = ColaboradoresIndexRouteImport.update({
  id: '/colaboradores/',
  path: '/colaboradores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaDeDocumentosIndexRoute = CaixaDeDocumentosIndexRouteImport.update({
  id: '/caixa-de-documentos/',
  path: '/caixa-de-documentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgendaRouteRoute,
} as any)
const ModelosDeDocumentosNovoRoute = ModelosDeDocumentosNovoRouteImport.update({
  id: '/modelos-de-documentos/novo',
  path: '/modelos-de-documentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosDeDocumentosDocumentSpecificationIdRoute =
  ModelosDeDocumentosDocumentSpecificationIdRouteImport.update({
    id: '/modelos-de-documentos/$documentSpecificationId',
    path: '/modelos-de-documentos/$documentSpecificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LotesDocumentosFileIdRoute = LotesDocumentosFileIdRouteImport.update({
  id: '/lotes-documentos/$fileId',
  path: '/lotes-documentos/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakesNovoRoute = IntakesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => IntakesRouteRoute,
} as any)
const IntakesIntakeIdRoute = IntakesIntakeIdRouteImport.update({
  id: '/$intakeId',
  path: '/$intakeId',
  getParentRoute: () => IntakesRouteRoute,
} as any)
const ColaboradoresColaboradorIdRoute =
  ColaboradoresColaboradorIdRouteImport.update({
    id: '/colaboradores/$colaboradorId',
    path: '/colaboradores/$colaboradorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientePrivacidadeRoute = ClientePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteMensagensRoute = ClienteMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const CaixaDeDocumentosFileIdRoute = CaixaDeDocumentosFileIdRouteImport.update({
  id: '/caixa-de-documentos/$fileId',
  path: '/caixa-de-documentos/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoDashboardRoute = AtendimentoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AtendimentoRouteRoute,
} as any)
const AtendimentoConsultasRoute = AtendimentoConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AtendimentoRouteRoute,
} as any)
const AdvogadoMeusCasosRoute = AdvogadoMeusCasosRouteImport.update({
  id: '/meus-casos',
  path: '/meus-casos',
  getParentRoute: () => AdvogadoRouteRoute,
} as any)
const AdvogadoComunicacaoRoute = AdvogadoComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => AdvogadoRouteRoute,
} as any)
const ConsultasConsultationIdRouteRoute =
  ConsultasConsultationIdRouteRouteImport.update({
    id: '/$consultationId',
    path: '/$consultationId',
    getParentRoute: () => ConsultasRouteRoute,
  } as any)
const ConsultasConsultationIdIndexRoute =
  ConsultasConsultationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsultasConsultationIdRouteRoute,
  } as any)
const ClienteMeusCasosIndexRoute = ClienteMeusCasosIndexRouteImport.update({
  id: '/meus-casos/',
  path: '/meus-casos/',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ConsultasConsultationIdFichaAtendimentoRoute =
  ConsultasConsultationIdFichaAtendimentoRouteImport.update({
    id: '/ficha-atendimento',
    path: '/ficha-atendimento',
    getParentRoute: () => ConsultasConsultationIdRouteRoute,
  } as any)
const ClienteMeusCasosCaseIdRoute = ClienteMeusCasosCaseIdRouteImport.update({
  id: '/meus-casos/$caseId',
  path: '/meus-casos/$caseId',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ConsultasConsultationIdDocumentosIndexRoute =
  ConsultasConsultationIdDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => ConsultasConsultationIdRouteRoute,
  } as any)
const ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute =
  ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRouteImport.update(
    {
      id: '/documentos/$documentId/versoes/$documentVersionId',
      path: '/documentos/$documentId/versoes/$documentVersionId',
      getParentRoute: () => ConsultasConsultationIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteRouteWithChildren
  '/agenda': typeof AgendaRouteRouteWithChildren
  '/atendimento': typeof AtendimentoRouteRouteWithChildren
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/consultas': typeof ConsultasRouteRouteWithChildren
  '/intakes': typeof IntakesRouteRouteWithChildren
  '/consultas/$consultationId': typeof ConsultasConsultationIdRouteRouteWithChildren
  '/advogado/comunicacao': typeof AdvogadoComunicacaoRoute
  '/advogado/meus-casos': typeof AdvogadoMeusCasosRoute
  '/atendimento/consultas': typeof AtendimentoConsultasRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/caixa-de-documentos/$fileId': typeof CaixaDeDocumentosFileIdRoute
  '/cliente/mensagens': typeof ClienteMensagensRoute
  '/cliente/privacidade': typeof ClientePrivacidadeRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/colaboradores/$colaboradorId': typeof ColaboradoresColaboradorIdRoute
  '/intakes/$intakeId': typeof IntakesIntakeIdRoute
  '/intakes/novo': typeof IntakesNovoRoute
  '/lotes-documentos/$fileId': typeof LotesDocumentosFileIdRoute
  '/modelos-de-documentos/$documentSpecificationId': typeof ModelosDeDocumentosDocumentSpecificationIdRoute
  '/modelos-de-documentos/novo': typeof ModelosDeDocumentosNovoRoute
  '/agenda/': typeof AgendaIndexRoute
  '/caixa-de-documentos/': typeof CaixaDeDocumentosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/colaboradores/': typeof ColaboradoresIndexRoute
  '/consultas/': typeof ConsultasIndexRoute
  '/convite/': typeof ConviteIndexRoute
  '/home/': typeof HomeIndexRoute
  '/intakes/': typeof IntakesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/modelos-de-documentos/': typeof ModelosDeDocumentosIndexRoute
  '/pedir-redefinir-senha/': typeof PedirRedefinirSenhaIndexRoute
  '/redefinir-senha/': typeof RedefinirSenhaIndexRoute
  '/cliente/meus-casos/$caseId': typeof ClienteMeusCasosCaseIdRoute
  '/consultas/$consultationId/ficha-atendimento': typeof ConsultasConsultationIdFichaAtendimentoRoute
  '/cliente/meus-casos/': typeof ClienteMeusCasosIndexRoute
  '/consultas/$consultationId/': typeof ConsultasConsultationIdIndexRoute
  '/consultas/$consultationId/documentos/': typeof ConsultasConsultationIdDocumentosIndexRoute
  '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId': typeof ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteRouteWithChildren
  '/atendimento': typeof AtendimentoRouteRouteWithChildren
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/advogado/comunicacao': typeof AdvogadoComunicacaoRoute
  '/advogado/meus-casos': typeof AdvogadoMeusCasosRoute
  '/atendimento/consultas': typeof AtendimentoConsultasRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/caixa-de-documentos/$fileId': typeof CaixaDeDocumentosFileIdRoute
  '/cliente/mensagens': typeof ClienteMensagensRoute
  '/cliente/privacidade': typeof ClientePrivacidadeRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/colaboradores/$colaboradorId': typeof ColaboradoresColaboradorIdRoute
  '/intakes/$intakeId': typeof IntakesIntakeIdRoute
  '/intakes/novo': typeof IntakesNovoRoute
  '/lotes-documentos/$fileId': typeof LotesDocumentosFileIdRoute
  '/modelos-de-documentos/$documentSpecificationId': typeof ModelosDeDocumentosDocumentSpecificationIdRoute
  '/modelos-de-documentos/novo': typeof ModelosDeDocumentosNovoRoute
  '/agenda': typeof AgendaIndexRoute
  '/caixa-de-documentos': typeof CaixaDeDocumentosIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/colaboradores': typeof ColaboradoresIndexRoute
  '/consultas': typeof ConsultasIndexRoute
  '/convite': typeof ConviteIndexRoute
  '/home': typeof HomeIndexRoute
  '/intakes': typeof IntakesIndexRoute
  '/login': typeof LoginIndexRoute
  '/modelos-de-documentos': typeof ModelosDeDocumentosIndexRoute
  '/pedir-redefinir-senha': typeof PedirRedefinirSenhaIndexRoute
  '/redefinir-senha': typeof RedefinirSenhaIndexRoute
  '/cliente/meus-casos/$caseId': typeof ClienteMeusCasosCaseIdRoute
  '/consultas/$consultationId/ficha-atendimento': typeof ConsultasConsultationIdFichaAtendimentoRoute
  '/cliente/meus-casos': typeof ClienteMeusCasosIndexRoute
  '/consultas/$consultationId': typeof ConsultasConsultationIdIndexRoute
  '/consultas/$consultationId/documentos': typeof ConsultasConsultationIdDocumentosIndexRoute
  '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId': typeof ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteRouteWithChildren
  '/agenda': typeof AgendaRouteRouteWithChildren
  '/atendimento': typeof AtendimentoRouteRouteWithChildren
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/consultas': typeof ConsultasRouteRouteWithChildren
  '/intakes': typeof IntakesRouteRouteWithChildren
  '/consultas/$consultationId': typeof ConsultasConsultationIdRouteRouteWithChildren
  '/advogado/comunicacao': typeof AdvogadoComunicacaoRoute
  '/advogado/meus-casos': typeof AdvogadoMeusCasosRoute
  '/atendimento/consultas': typeof AtendimentoConsultasRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/caixa-de-documentos/$fileId': typeof CaixaDeDocumentosFileIdRoute
  '/cliente/mensagens': typeof ClienteMensagensRoute
  '/cliente/privacidade': typeof ClientePrivacidadeRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/colaboradores/$colaboradorId': typeof ColaboradoresColaboradorIdRoute
  '/intakes/$intakeId': typeof IntakesIntakeIdRoute
  '/intakes/novo': typeof IntakesNovoRoute
  '/lotes-documentos/$fileId': typeof LotesDocumentosFileIdRoute
  '/modelos-de-documentos/$documentSpecificationId': typeof ModelosDeDocumentosDocumentSpecificationIdRoute
  '/modelos-de-documentos/novo': typeof ModelosDeDocumentosNovoRoute
  '/agenda/': typeof AgendaIndexRoute
  '/caixa-de-documentos/': typeof CaixaDeDocumentosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/colaboradores/': typeof ColaboradoresIndexRoute
  '/consultas/': typeof ConsultasIndexRoute
  '/convite/': typeof ConviteIndexRoute
  '/home/': typeof HomeIndexRoute
  '/intakes/': typeof IntakesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/modelos-de-documentos/': typeof ModelosDeDocumentosIndexRoute
  '/pedir-redefinir-senha/': typeof PedirRedefinirSenhaIndexRoute
  '/redefinir-senha/': typeof RedefinirSenhaIndexRoute
  '/cliente/meus-casos/$caseId': typeof ClienteMeusCasosCaseIdRoute
  '/consultas/$consultationId/ficha-atendimento': typeof ConsultasConsultationIdFichaAtendimentoRoute
  '/cliente/meus-casos/': typeof ClienteMeusCasosIndexRoute
  '/consultas/$consultationId/': typeof ConsultasConsultationIdIndexRoute
  '/consultas/$consultationId/documentos/': typeof ConsultasConsultationIdDocumentosIndexRoute
  '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId': typeof ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advogado'
    | '/agenda'
    | '/atendimento'
    | '/cliente'
    | '/consultas'
    | '/intakes'
    | '/consultas/$consultationId'
    | '/advogado/comunicacao'
    | '/advogado/meus-casos'
    | '/atendimento/consultas'
    | '/atendimento/dashboard'
    | '/caixa-de-documentos/$fileId'
    | '/cliente/mensagens'
    | '/cliente/privacidade'
    | '/clientes/$clienteId'
    | '/colaboradores/$colaboradorId'
    | '/intakes/$intakeId'
    | '/intakes/novo'
    | '/lotes-documentos/$fileId'
    | '/modelos-de-documentos/$documentSpecificationId'
    | '/modelos-de-documentos/novo'
    | '/agenda/'
    | '/caixa-de-documentos/'
    | '/clientes/'
    | '/colaboradores/'
    | '/consultas/'
    | '/convite/'
    | '/home/'
    | '/intakes/'
    | '/login/'
    | '/modelos-de-documentos/'
    | '/pedir-redefinir-senha/'
    | '/redefinir-senha/'
    | '/cliente/meus-casos/$caseId'
    | '/consultas/$consultationId/ficha-atendimento'
    | '/cliente/meus-casos/'
    | '/consultas/$consultationId/'
    | '/consultas/$consultationId/documentos/'
    | '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advogado'
    | '/atendimento'
    | '/cliente'
    | '/advogado/comunicacao'
    | '/advogado/meus-casos'
    | '/atendimento/consultas'
    | '/atendimento/dashboard'
    | '/caixa-de-documentos/$fileId'
    | '/cliente/mensagens'
    | '/cliente/privacidade'
    | '/clientes/$clienteId'
    | '/colaboradores/$colaboradorId'
    | '/intakes/$intakeId'
    | '/intakes/novo'
    | '/lotes-documentos/$fileId'
    | '/modelos-de-documentos/$documentSpecificationId'
    | '/modelos-de-documentos/novo'
    | '/agenda'
    | '/caixa-de-documentos'
    | '/clientes'
    | '/colaboradores'
    | '/consultas'
    | '/convite'
    | '/home'
    | '/intakes'
    | '/login'
    | '/modelos-de-documentos'
    | '/pedir-redefinir-senha'
    | '/redefinir-senha'
    | '/cliente/meus-casos/$caseId'
    | '/consultas/$consultationId/ficha-atendimento'
    | '/cliente/meus-casos'
    | '/consultas/$consultationId'
    | '/consultas/$consultationId/documentos'
    | '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'
  id:
    | '__root__'
    | '/'
    | '/advogado'
    | '/agenda'
    | '/atendimento'
    | '/cliente'
    | '/consultas'
    | '/intakes'
    | '/consultas/$consultationId'
    | '/advogado/comunicacao'
    | '/advogado/meus-casos'
    | '/atendimento/consultas'
    | '/atendimento/dashboard'
    | '/caixa-de-documentos/$fileId'
    | '/cliente/mensagens'
    | '/cliente/privacidade'
    | '/clientes/$clienteId'
    | '/colaboradores/$colaboradorId'
    | '/intakes/$intakeId'
    | '/intakes/novo'
    | '/lotes-documentos/$fileId'
    | '/modelos-de-documentos/$documentSpecificationId'
    | '/modelos-de-documentos/novo'
    | '/agenda/'
    | '/caixa-de-documentos/'
    | '/clientes/'
    | '/colaboradores/'
    | '/consultas/'
    | '/convite/'
    | '/home/'
    | '/intakes/'
    | '/login/'
    | '/modelos-de-documentos/'
    | '/pedir-redefinir-senha/'
    | '/redefinir-senha/'
    | '/cliente/meus-casos/$caseId'
    | '/consultas/$consultationId/ficha-atendimento'
    | '/cliente/meus-casos/'
    | '/consultas/$consultationId/'
    | '/consultas/$consultationId/documentos/'
    | '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadoRouteRoute: typeof AdvogadoRouteRouteWithChildren
  AgendaRouteRoute: typeof AgendaRouteRouteWithChildren
  AtendimentoRouteRoute: typeof AtendimentoRouteRouteWithChildren
  ClienteRouteRoute: typeof ClienteRouteRouteWithChildren
  ConsultasRouteRoute: typeof ConsultasRouteRouteWithChildren
  IntakesRouteRoute: typeof IntakesRouteRouteWithChildren
  CaixaDeDocumentosFileIdRoute: typeof CaixaDeDocumentosFileIdRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ColaboradoresColaboradorIdRoute: typeof ColaboradoresColaboradorIdRoute
  LotesDocumentosFileIdRoute: typeof LotesDocumentosFileIdRoute
  ModelosDeDocumentosDocumentSpecificationIdRoute: typeof ModelosDeDocumentosDocumentSpecificationIdRoute
  ModelosDeDocumentosNovoRoute: typeof ModelosDeDocumentosNovoRoute
  CaixaDeDocumentosIndexRoute: typeof CaixaDeDocumentosIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ColaboradoresIndexRoute: typeof ColaboradoresIndexRoute
  ConviteIndexRoute: typeof ConviteIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ModelosDeDocumentosIndexRoute: typeof ModelosDeDocumentosIndexRoute
  PedirRedefinirSenhaIndexRoute: typeof PedirRedefinirSenhaIndexRoute
  RedefinirSenhaIndexRoute: typeof RedefinirSenhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intakes': {
      id: '/intakes'
      path: '/intakes'
      fullPath: '/intakes'
      preLoaderRoute: typeof IntakesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogado': {
      id: '/advogado'
      path: '/advogado'
      fullPath: '/advogado'
      preLoaderRoute: typeof AdvogadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha/': {
      id: '/redefinir-senha/'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha/'
      preLoaderRoute: typeof RedefinirSenhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir-redefinir-senha/': {
      id: '/pedir-redefinir-senha/'
      path: '/pedir-redefinir-senha'
      fullPath: '/pedir-redefinir-senha/'
      preLoaderRoute: typeof PedirRedefinirSenhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos-de-documentos/': {
      id: '/modelos-de-documentos/'
      path: '/modelos-de-documentos'
      fullPath: '/modelos-de-documentos/'
      preLoaderRoute: typeof ModelosDeDocumentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intakes/': {
      id: '/intakes/'
      path: '/'
      fullPath: '/intakes/'
      preLoaderRoute: typeof IntakesIndexRouteImport
      parentRoute: typeof IntakesRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/': {
      id: '/convite/'
      path: '/convite'
      fullPath: '/convite/'
      preLoaderRoute: typeof ConviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas/': {
      id: '/consultas/'
      path: '/'
      fullPath: '/consultas/'
      preLoaderRoute: typeof ConsultasIndexRouteImport
      parentRoute: typeof ConsultasRouteRoute
    }
    '/colaboradores/': {
      id: '/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof ColaboradoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-de-documentos/': {
      id: '/caixa-de-documentos/'
      path: '/caixa-de-documentos'
      fullPath: '/caixa-de-documentos/'
      preLoaderRoute: typeof CaixaDeDocumentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof AgendaRouteRoute
    }
    '/modelos-de-documentos/novo': {
      id: '/modelos-de-documentos/novo'
      path: '/modelos-de-documentos/novo'
      fullPath: '/modelos-de-documentos/novo'
      preLoaderRoute: typeof ModelosDeDocumentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos-de-documentos/$documentSpecificationId': {
      id: '/modelos-de-documentos/$documentSpecificationId'
      path: '/modelos-de-documentos/$documentSpecificationId'
      fullPath: '/modelos-de-documentos/$documentSpecificationId'
      preLoaderRoute: typeof ModelosDeDocumentosDocumentSpecificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes-documentos/$fileId': {
      id: '/lotes-documentos/$fileId'
      path: '/lotes-documentos/$fileId'
      fullPath: '/lotes-documentos/$fileId'
      preLoaderRoute: typeof LotesDocumentosFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intakes/novo': {
      id: '/intakes/novo'
      path: '/novo'
      fullPath: '/intakes/novo'
      preLoaderRoute: typeof IntakesNovoRouteImport
      parentRoute: typeof IntakesRouteRoute
    }
    '/intakes/$intakeId': {
      id: '/intakes/$intakeId'
      path: '/$intakeId'
      fullPath: '/intakes/$intakeId'
      preLoaderRoute: typeof IntakesIntakeIdRouteImport
      parentRoute: typeof IntakesRouteRoute
    }
    '/colaboradores/$colaboradorId': {
      id: '/colaboradores/$colaboradorId'
      path: '/colaboradores/$colaboradorId'
      fullPath: '/colaboradores/$colaboradorId'
      preLoaderRoute: typeof ColaboradoresColaboradorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/privacidade': {
      id: '/cliente/privacidade'
      path: '/privacidade'
      fullPath: '/cliente/privacidade'
      preLoaderRoute: typeof ClientePrivacidadeRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/mensagens': {
      id: '/cliente/mensagens'
      path: '/mensagens'
      fullPath: '/cliente/mensagens'
      preLoaderRoute: typeof ClienteMensagensRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/caixa-de-documentos/$fileId': {
      id: '/caixa-de-documentos/$fileId'
      path: '/caixa-de-documentos/$fileId'
      fullPath: '/caixa-de-documentos/$fileId'
      preLoaderRoute: typeof CaixaDeDocumentosFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/dashboard': {
      id: '/atendimento/dashboard'
      path: '/dashboard'
      fullPath: '/atendimento/dashboard'
      preLoaderRoute: typeof AtendimentoDashboardRouteImport
      parentRoute: typeof AtendimentoRouteRoute
    }
    '/atendimento/consultas': {
      id: '/atendimento/consultas'
      path: '/consultas'
      fullPath: '/atendimento/consultas'
      preLoaderRoute: typeof AtendimentoConsultasRouteImport
      parentRoute: typeof AtendimentoRouteRoute
    }
    '/advogado/meus-casos': {
      id: '/advogado/meus-casos'
      path: '/meus-casos'
      fullPath: '/advogado/meus-casos'
      preLoaderRoute: typeof AdvogadoMeusCasosRouteImport
      parentRoute: typeof AdvogadoRouteRoute
    }
    '/advogado/comunicacao': {
      id: '/advogado/comunicacao'
      path: '/comunicacao'
      fullPath: '/advogado/comunicacao'
      preLoaderRoute: typeof AdvogadoComunicacaoRouteImport
      parentRoute: typeof AdvogadoRouteRoute
    }
    '/consultas/$consultationId': {
      id: '/consultas/$consultationId'
      path: '/$consultationId'
      fullPath: '/consultas/$consultationId'
      preLoaderRoute: typeof ConsultasConsultationIdRouteRouteImport
      parentRoute: typeof ConsultasRouteRoute
    }
    '/consultas/$consultationId/': {
      id: '/consultas/$consultationId/'
      path: '/'
      fullPath: '/consultas/$consultationId/'
      preLoaderRoute: typeof ConsultasConsultationIdIndexRouteImport
      parentRoute: typeof ConsultasConsultationIdRouteRoute
    }
    '/cliente/meus-casos/': {
      id: '/cliente/meus-casos/'
      path: '/meus-casos'
      fullPath: '/cliente/meus-casos/'
      preLoaderRoute: typeof ClienteMeusCasosIndexRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/consultas/$consultationId/ficha-atendimento': {
      id: '/consultas/$consultationId/ficha-atendimento'
      path: '/ficha-atendimento'
      fullPath: '/consultas/$consultationId/ficha-atendimento'
      preLoaderRoute: typeof ConsultasConsultationIdFichaAtendimentoRouteImport
      parentRoute: typeof ConsultasConsultationIdRouteRoute
    }
    '/cliente/meus-casos/$caseId': {
      id: '/cliente/meus-casos/$caseId'
      path: '/meus-casos/$caseId'
      fullPath: '/cliente/meus-casos/$caseId'
      preLoaderRoute: typeof ClienteMeusCasosCaseIdRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/consultas/$consultationId/documentos/': {
      id: '/consultas/$consultationId/documentos/'
      path: '/documentos'
      fullPath: '/consultas/$consultationId/documentos/'
      preLoaderRoute: typeof ConsultasConsultationIdDocumentosIndexRouteImport
      parentRoute: typeof ConsultasConsultationIdRouteRoute
    }
    '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId': {
      id: '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'
      path: '/documentos/$documentId/versoes/$documentVersionId'
      fullPath: '/consultas/$consultationId/documentos/$documentId/versoes/$documentVersionId'
      preLoaderRoute: typeof ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRouteImport
      parentRoute: typeof ConsultasConsultationIdRouteRoute
    }
  }
}

interface AdvogadoRouteRouteChildren {
  AdvogadoComunicacaoRoute: typeof AdvogadoComunicacaoRoute
  AdvogadoMeusCasosRoute: typeof AdvogadoMeusCasosRoute
}

const AdvogadoRouteRouteChildren: AdvogadoRouteRouteChildren = {
  AdvogadoComunicacaoRoute: AdvogadoComunicacaoRoute,
  AdvogadoMeusCasosRoute: AdvogadoMeusCasosRoute,
}

const AdvogadoRouteRouteWithChildren = AdvogadoRouteRoute._addFileChildren(
  AdvogadoRouteRouteChildren,
)

interface AgendaRouteRouteChildren {
  AgendaIndexRoute: typeof AgendaIndexRoute
}

const AgendaRouteRouteChildren: AgendaRouteRouteChildren = {
  AgendaIndexRoute: AgendaIndexRoute,
}

const AgendaRouteRouteWithChildren = AgendaRouteRoute._addFileChildren(
  AgendaRouteRouteChildren,
)

interface AtendimentoRouteRouteChildren {
  AtendimentoConsultasRoute: typeof AtendimentoConsultasRoute
  AtendimentoDashboardRoute: typeof AtendimentoDashboardRoute
}

const AtendimentoRouteRouteChildren: AtendimentoRouteRouteChildren = {
  AtendimentoConsultasRoute: AtendimentoConsultasRoute,
  AtendimentoDashboardRoute: AtendimentoDashboardRoute,
}

const AtendimentoRouteRouteWithChildren =
  AtendimentoRouteRoute._addFileChildren(AtendimentoRouteRouteChildren)

interface ClienteRouteRouteChildren {
  ClienteMensagensRoute: typeof ClienteMensagensRoute
  ClientePrivacidadeRoute: typeof ClientePrivacidadeRoute
  ClienteMeusCasosCaseIdRoute: typeof ClienteMeusCasosCaseIdRoute
  ClienteMeusCasosIndexRoute: typeof ClienteMeusCasosIndexRoute
}

const ClienteRouteRouteChildren: ClienteRouteRouteChildren = {
  ClienteMensagensRoute: ClienteMensagensRoute,
  ClientePrivacidadeRoute: ClientePrivacidadeRoute,
  ClienteMeusCasosCaseIdRoute: ClienteMeusCasosCaseIdRoute,
  ClienteMeusCasosIndexRoute: ClienteMeusCasosIndexRoute,
}

const ClienteRouteRouteWithChildren = ClienteRouteRoute._addFileChildren(
  ClienteRouteRouteChildren,
)

interface ConsultasConsultationIdRouteRouteChildren {
  ConsultasConsultationIdFichaAtendimentoRoute: typeof ConsultasConsultationIdFichaAtendimentoRoute
  ConsultasConsultationIdIndexRoute: typeof ConsultasConsultationIdIndexRoute
  ConsultasConsultationIdDocumentosIndexRoute: typeof ConsultasConsultationIdDocumentosIndexRoute
  ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute: typeof ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute
}

const ConsultasConsultationIdRouteRouteChildren: ConsultasConsultationIdRouteRouteChildren =
  {
    ConsultasConsultationIdFichaAtendimentoRoute:
      ConsultasConsultationIdFichaAtendimentoRoute,
    ConsultasConsultationIdIndexRoute: ConsultasConsultationIdIndexRoute,
    ConsultasConsultationIdDocumentosIndexRoute:
      ConsultasConsultationIdDocumentosIndexRoute,
    ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute:
      ConsultasConsultationIdDocumentosDocumentIdVersoesDocumentVersionIdRoute,
  }

const ConsultasConsultationIdRouteRouteWithChildren =
  ConsultasConsultationIdRouteRoute._addFileChildren(
    ConsultasConsultationIdRouteRouteChildren,
  )

interface ConsultasRouteRouteChildren {
  ConsultasConsultationIdRouteRoute: typeof ConsultasConsultationIdRouteRouteWithChildren
  ConsultasIndexRoute: typeof ConsultasIndexRoute
}

const ConsultasRouteRouteChildren: ConsultasRouteRouteChildren = {
  ConsultasConsultationIdRouteRoute:
    ConsultasConsultationIdRouteRouteWithChildren,
  ConsultasIndexRoute: ConsultasIndexRoute,
}

const ConsultasRouteRouteWithChildren = ConsultasRouteRoute._addFileChildren(
  ConsultasRouteRouteChildren,
)

interface IntakesRouteRouteChildren {
  IntakesIntakeIdRoute: typeof IntakesIntakeIdRoute
  IntakesNovoRoute: typeof IntakesNovoRoute
  IntakesIndexRoute: typeof IntakesIndexRoute
}

const IntakesRouteRouteChildren: IntakesRouteRouteChildren = {
  IntakesIntakeIdRoute: IntakesIntakeIdRoute,
  IntakesNovoRoute: IntakesNovoRoute,
  IntakesIndexRoute: IntakesIndexRoute,
}

const IntakesRouteRouteWithChildren = IntakesRouteRoute._addFileChildren(
  IntakesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadoRouteRoute: AdvogadoRouteRouteWithChildren,
  AgendaRouteRoute: AgendaRouteRouteWithChildren,
  AtendimentoRouteRoute: AtendimentoRouteRouteWithChildren,
  ClienteRouteRoute: ClienteRouteRouteWithChildren,
  ConsultasRouteRoute: ConsultasRouteRouteWithChildren,
  IntakesRouteRoute: IntakesRouteRouteWithChildren,
  CaixaDeDocumentosFileIdRoute: CaixaDeDocumentosFileIdRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ColaboradoresColaboradorIdRoute: ColaboradoresColaboradorIdRoute,
  LotesDocumentosFileIdRoute: LotesDocumentosFileIdRoute,
  ModelosDeDocumentosDocumentSpecificationIdRoute:
    ModelosDeDocumentosDocumentSpecificationIdRoute,
  ModelosDeDocumentosNovoRoute: ModelosDeDocumentosNovoRoute,
  CaixaDeDocumentosIndexRoute: CaixaDeDocumentosIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ColaboradoresIndexRoute: ColaboradoresIndexRoute,
  ConviteIndexRoute: ConviteIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ModelosDeDocumentosIndexRoute: ModelosDeDocumentosIndexRoute,
  PedirRedefinirSenhaIndexRoute: PedirRedefinirSenhaIndexRoute,
  RedefinirSenhaIndexRoute: RedefinirSenhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
