import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ChartLine,
  Check,
  Circle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Coins,
  Copy,
  DoorOpen,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  FileText,
  History,
  IdCard,
  Inbox,
  LayoutDashboard,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Monitor,
  Pencil,
  Phone,
  Pilcrow,
  Plus,
  Quote,
  RefreshCw,
  RemoveFormatting,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Strikethrough,
  Tag,
  TriangleAlert,
  Trash2,
  Undo,
  Redo,
  User,
  UserRoundX,
  Users,
  Video,
  X,
  ZoomIn,
  ZoomOut,
  Underline,
  Info,
} from 'lucide-react'

import type { LucideIcon as LucideIconComponent } from 'lucide-react'
import type { IconName } from '../types'

export const ICONS: Record<IconName, LucideIconComponent> = {
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,

  check: Check,
  circle: Circle,

  'clipboard-list': ClipboardList,
  'file-text': FileText,
  'layout-dashboard': LayoutDashboard,
  inbox: Inbox,

  'briefcase-business': BriefcaseBusiness,
  'calendar-days': CalendarDays,

  users: Users,
  user: User,
  building: Building,

  settings: Settings,
  coins: Coins,
  'chart-line': ChartLine,
  'list-search': List,

  monitor: Monitor,
  calendar: Calendar,
  briefcase: Briefcase,
  bell: Bell,

  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,

  clock: Clock,
  'list-checks': ListChecks,

  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,

  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  'messages-square': MessagesSquare,

  phone: Phone,
  scale: Scale,
  search: Search,
  send: Send,

  'shield-check': ShieldCheck,

  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'door-open': DoorOpen,
  'external-link': ExternalLink,

  eye: Eye,
  ellipsis: Ellipsis,
  history: History,
  'id-card': IdCard,
  'list-plus': ListPlus,
  pencil: Pencil,
  info: Info,

  plus: Plus,
  'refresh-cw': RefreshCw,
  tag: Tag,
  'triangle-alert': TriangleAlert,
  'trash-2': Trash2,

  'user-x': UserRoundX,
  video: Video,
  x: X,

  pilcrow: Pilcrow,
  quote: Quote,
  'list-ordered': ListOrdered,
  strikethrough: Strikethrough,

  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,

  'remove-formatting': RemoveFormatting,

  undo: Undo,
  redo: Redo,

  link: Link,
  copy: Copy,

  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,

  download: Download,
  underline: Underline,
}
