import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ChartLine,
  Check,
  Circle,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  Coins,
  DoorOpen,
  Ellipsis,
  ExternalLink,
  Eye,
  FileText,
  History,
  IdCard,
  Inbox,
  Info,
  LayoutDashboard,
  List,
  ListChecks,
  ListPlus,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Monitor,
  Phone,
  Pencil,
  Plus,
  RefreshCw,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Tag,
  TriangleAlert,
  User,
  UserRoundX,
  Users,
  Video,
  X,
  Pilcrow,
  Quote,
  ListOrdered,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  RemoveFormatting,
  Undo,
  Redo,
  Link,
  Trash2,
  Copy,
  ZoomIn,
  ZoomOut,
  ChevronUp,
  ChevronDown,
  Timer,
  Loader2,
  Lock,
  Package,
  Sparkles,
  AlertCircle,
  Building2,
  FileEdit,
  RotateCcw,
  CheckCircle2,
  XCircle,
} from 'lucide-react'
import type { LucideIcon as LucideIconComponent } from 'lucide-react'
import type { IconName } from '../types'

export const ICONS: Record<IconName, LucideIconComponent> = {
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  check: Check,
  circle: Circle,
  'clipboard-list': ClipboardList,
  'file-text': FileText,
  'layout-dashboard': LayoutDashboard,
  inbox: Inbox,
  'briefcase-business': BriefcaseBusiness,
  'calendar-days': CalendarDays,
  users: Users,
  user: User,
  building: Building,
  settings: Settings,
  coins: Coins,
  'chart-line': ChartLine,
  'list-search': List,
  monitor: Monitor,
  calendar: Calendar,
  briefcase: Briefcase,
  bell: Bell,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  'list-checks': ListChecks,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  phone: Phone,
  scale: Scale,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'door-open': DoorOpen,
  'external-link': ExternalLink,
  eye: Eye,
  ellipsis: Ellipsis,
  history: History,
  'id-card': IdCard,
  'list-plus': ListPlus,
  pencil: Pencil,
  info: Info,
  'messages-square': MessagesSquare,
  plus: Plus,
  'refresh-cw': RefreshCw,
  tag: Tag,
  'triangle-alert': TriangleAlert,
  'user-x': UserRoundX,
  video: Video,
  x: X,
  pilcrow: Pilcrow,
  quote: Quote,
  'list-ordered': ListOrdered,
  strikethrough: Strikethrough,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'remove-formatting': RemoveFormatting,
  undo: Undo,
  redo: Redo,
  link: Link,
  'trash-2': Trash2,
  copy: Copy,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  timer: Timer,
  'loader-2': Loader2,
  lock: Lock,
  package: Package,
  sparkles: Sparkles,
  'alert-circle': AlertCircle,
  'building-2': Building2,
  'file-edit': FileEdit,
  'rotate-ccw': RotateCcw,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
}
