@baseUrl = {{BASE_URL}}
@clientId = replace-with-client-uuid

### List document batches for a client
GET {{baseUrl}}/document-batches/clients/{{clientId}}
Accept: application/json

### Get a document file
# Copy fileId from the document batch response.
# @prompt fileId Copy the document file ID
GET {{baseUrl}}/documents/files/{{fileId}}
Accept: application/json
