export { CloseIntakeWithoutContractController } from '@/intake/rest/controllers/close-intake-without-contract.controller'
export { GetIntakesController } from '@/intake/rest/controllers/get-intake.controller'
export { ListClientIntakesController } from '@/intake/rest/controllers/list-client-intakes.controller'
export { RegisterIntakesController } from '@/intake/rest/controllers/register-intake.controller'
export { TransitionIntakeStatusController } from '@/intake/rest/controllers/transition-intake-status.controller'
