@url = {{BASE_URL}}/auth

# @prompt seedPassword Enter HMS_USER_SEED_PASSWORD

### Sign in
# @name signIn
POST {{url}}/sign-in
Content-Type: application/json

{
  "identifier": "lawyer@hmsadvogados.com.br",
  "password": "{{seedPassword}}"
}

### Complete collaborator sign-in
# Use the access token returned by Sign in.
POST {{url}}/complete-sign-in
Authorization: Bearer {{signIn.response.body.$.accessToken}}
