@baseUrl = http://localhost:3333
@email = admin@hmsadvogados.com.br
@senha = password123

### 1. Login terminal a
# @name loginTerminalA
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "identificador": "{{email}}",
  "senha": "{{senha}}"
}

###
@tokenA = {{loginTerminalA.response.body.accessToken}}

### 2. Acessar Rota com terminal a
GET {{baseUrl}}/session-test
Authorization: Bearer {{tokenA}}

### 3. Login terminal b
# @name loginTerminalB
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "identificador": "{{email}}",
  "senha": "{{senha}}"
}

###
@tokenB = {{loginTerminalB.response.body.accessToken}}

### 4. Acessar com terminal b 
GET {{baseUrl}}/session-test
Authorization: Bearer {{tokenB}}

### 5. Acessar rota novamente com terminal a
GET {{baseUrl}}/session-test
Authorization: Bearer {{tokenA}}