@url = {{BASE_URL}}/legal-catalog
@legalAreaId = 276ab847-912b-4601-b6c4-e915ad93b7f6

### List active legal areas
GET {{url}}/areas
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### List active topics for a legal area
GET {{url}}/areas/{{legalAreaId}}/topics
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
