@url = {{BASE_URL}}/legal-catalog
@legalAreaId = replace-with-legal-area-uuid

### List active legal areas
GET {{url}}/areas
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

### List active topics for a legal area
GET {{url}}/areas/{{legalAreaId}}/topics
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
